// <auto-generated />
using System;
using Billing.RepositoryPattern.InfraStructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Billing.RepositoryPattern.InfraStructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231124171756_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.AuditableEntity", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.ToTable("Auditable", "Admin");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.BillingInfoEntity", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillingId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomersCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillingId");

                    b.HasIndex("CustomersCustomerId");

                    b.ToTable("BillingInfo", "Product");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.CustomersEntity", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers", "Product");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.MainMenuEntity", b =>
                {
                    b.Property<int>("MainMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MainMenuId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("HideFlag")
                        .HasColumnType("bit");

                    b.Property<string>("MainMenuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuSortOrder")
                        .HasColumnType("int");

                    b.HasKey("MainMenuId");

                    b.ToTable("MainMenu", "Admin");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.ProductsEntity", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", "Product");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.RolesEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Desription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "Admin");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.SalesDetailsEntity", b =>
                {
                    b.Property<int>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalesId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillingId")
                        .HasColumnType("int");

                    b.Property<int?>("BillingInfoBillingId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductsProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SalesId");

                    b.HasIndex("BillingInfoBillingId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("SalesDetails", "Product");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.SubMenuEntity", b =>
                {
                    b.Property<int>("SubMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubMenuId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HideFlag")
                        .HasColumnType("bit");

                    b.Property<int>("MainMenuId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesRoleId")
                        .HasColumnType("int");

                    b.Property<string>("SubMenuName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubMenuSortOrder")
                        .HasColumnType("int");

                    b.HasKey("SubMenuId");

                    b.HasIndex("MainMenuId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("SubMenu", "Admin");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<int?>("AuditableAuditId")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("RolesRoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("AuditableAuditId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("Users", "Admin");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.BillingInfoEntity", b =>
                {
                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.CustomersEntity", "Customers")
                        .WithMany()
                        .HasForeignKey("CustomersCustomerId");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.SalesDetailsEntity", b =>
                {
                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.BillingInfoEntity", "BillingInfo")
                        .WithMany()
                        .HasForeignKey("BillingInfoBillingId");

                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.ProductsEntity", "Products")
                        .WithMany()
                        .HasForeignKey("ProductsProductId");

                    b.Navigation("BillingInfo");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.SubMenuEntity", b =>
                {
                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.MainMenuEntity", "MainMenu")
                        .WithMany("SubMenuList")
                        .HasForeignKey("MainMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.RolesEntity", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesRoleId");

                    b.Navigation("MainMenu");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.UserEntity", b =>
                {
                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.AuditableEntity", "Auditable")
                        .WithMany()
                        .HasForeignKey("AuditableAuditId");

                    b.HasOne("Billing.RepositoryPattern.Domain.DbEntities.RolesEntity", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesRoleId");

                    b.Navigation("Auditable");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Billing.RepositoryPattern.Domain.DbEntities.MainMenuEntity", b =>
                {
                    b.Navigation("SubMenuList");
                });
#pragma warning restore 612, 618
        }
    }
}
